### ISSUE TITLE
Required properties marked as optional.

### ISSUE THREAD

**Issue by csuriel** [jpolanco91/react-movie-app#7]
Here you can get only the value you are using, e.g.:
```js
const {config: { API_URL }} = this.props;
```
https://github.com/jpolanco91/react-movie-app/blob/ca3bf5892c861fb9c245d72d2e0d4a41ef54f5d7/app/components/App.js#L14

Also, this property seems to be required in `componentDidMount()` so it may be better to have it like so in the propTypes.

https://github.com/jpolanco91/react-movie-app/blob/ca3bf5892c861fb9c245d72d2e0d4a41ef54f5d7/app/components/App.js#L43

**Comment by jpolanco91** [comment]
Closing as this was solved with MOV-03 (PR #4)
